---
title: "lab7"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(broom)

library(sf)
library(tmap)

```

# Part 1: Spatial data wrangling, visualization

## A. California county outlines (polygons)

```{r}
ca_counties_sf <- read_sf(here('data/ca_counties/CA_Counties_TIGER2016.shp'))

ca_subset_sf <- ca_counties_sf %>% 
  janitor::clean_names() %>% 
  select(country_name = name, land_area = aland)

ca_counties_df <- ca_counties_sf %>% 
  as.data.frame() %>% 
  select(-geometry)
  
```

### Examie and set CRS

```{r}
ca_subset_sf %>% 
  st_crs()

ca_subset_sf %>% 
  raster::crs()
```

```{r}
ggplot(data = ca_subset_sf) +
  geom_sf(aes(fill = land_area), color = 'white', size = 0.1) +
  theme_void() +
  scale_fill_gradientn(colors = c('cyan', 'blue', 'purple'))
```

### B. Invasive Red sesbania records (spatial points)

```{r}
sesbania_sf <- read_sf(here('data/red_sesbania', 'ds80.shp')) %>% 
  janitor::clean_names()

### check CRS
sesbania_sf %>% st_crs()
sesbania_sf %>% raster::crs()

### if you know the EPSG
sesbania_3857_sf <- st_transform(sesbania_sf, 3857)

### if you don't know the EPSG code
sesbania_3857_2_sf <- st_transform(sesbania_sf, st_crs(ca_subset_sf))

### check new one
sesbania_3857_sf %>% 
  st_crs()

```

### Plot them together!

```{r}
ggplot() +
  geom_sf(data = ca_subset_sf) +
  geom_sf(data = sesbania_3857_sf, size = 1, color = 'red')
```


### Wrangle to find sesbania observations per county

```{r}
ca_sesb_sf <- ca_subset_sf %>% 
  st_join(sesbania_3857_sf)

head(ca_sesb_sf)
```

```{r}
sesb_counts_sf <- ca_sesb_sf %>% 
  group_by(country_name) %>% 
  summarize(n_records = sum(!is.na(id)))

head(sesb_counts_sf)
```



```{r}
ggplot(data = sesb_counts_sf) +
  geom_sf(aes(fill = n_records),
          color = 'white', size = 0.1) +
  scale_fill_gradientn(colors = c('lightgrey', 'orange', 'red')) +
  theme_minimal() +
  labs(fill = 'Number of S. punicea records')
```

### Filter to just occurrences in Solano County

```{r}
### subset based on Solano County
solano_sesb_sf <- sesbania_3857_sf %>% 
  filter(county == 'Solano')

### subset counties based on Solano
solano_sf <- ca_subset_sf %>% 
  filter(country_name == 'Solano')

ggplot() +
  geom_sf(data = solano_sf) +
  geom_sf(data = solano_sesb_sf, color = 'red')
```


```{r}

tmap_mode(mode = 'view') +
tm_shape(ca_subset_sf) +
  tm_fill('land_area', palette = 'BuGn') +
  tm_shape(sesbania_3857_sf) +
  tm_dots()
```


